"""
script para definir o esquema dos dados da camada trusted do historico de veiculos.
"""

import polars as pl

HISTORICO_VEICULOS_SCHEMA: dict = {
    "cod_concessionaria": pl.String,
    "cod_filial": pl.String,
    "nome_da_concessionaria": pl.Utf8,
    "nome_da_filial": pl.Utf8,
    "marca_da_filial": pl.Utf8,
    "data_da_venda": pl.Date,
    "quantidade_vendida": pl.Int64,
    "valor_da_venda": pl.Float64,
    "custo_do_veiculo": pl.Float64,
    "lucro_da_venda": pl.Float64,
    "margem_da_venda": pl.Float64,
    "marca_do_veiculo": pl.Utf8,
    "modelo_do_veiculo": pl.Utf8,
    "familia_do_veiculo": pl.Utf8,
    "categoria_do_veiculo": pl.Utf8,
    "cor_do_veiculo": pl.Utf8,
    "veiculo_novo_ou_semi_novo": pl.Utf8,
    "tipo_do_combustivel": pl.Utf8,
    "ano_modelo_do_veiculo": pl.Date,
    "ano_fabricacao_do_veiculo": pl.Date,
    "dias_que_o_carro_ficou_no_estoque": pl.String,
    "tipo_de_venda_do_veiculo": pl.Utf8,
    "nome_do_vendedor_que_realizou_a_venda": pl.Utf8,
    "nome_do_comprador_do_veiculo": pl.Utf8,
    "cidade_da_venda": pl.Utf8,
    "estado_brasileiro_da_venda": pl.Utf8,
    "macroregiao_geografica_da_venda": pl.Utf8,
    "coluna_extra": pl.String,
    "cod_filial_ajustado": pl.String,
    "linha_duplicada": pl.Boolean,
    "linha_duplicada_parcial": pl.Boolean,
    "status_duplicidade": pl.Utf8,
    "colunas_deslocadas_e_repetidas": pl.Utf8,
    "tipo_de_venda_do_veiculo_ajustado": pl.Utf8,
    "nome_do_vendedor_que_realizou_a_venda_ajustado": pl.Utf8,
    "nome_do_comprador_do_veiculo_ajustado": pl.Utf8,
    "cidade_da_venda_ajustado": pl.Utf8,
    "estado_brasileiro_da_venda_ajustado": pl.Utf8,
    "macroregiao_geografica_da_venda_ajustado": pl.Utf8,
    "dias_que_o_carro_ficou_no_estoque_ajustado": pl.Int64,
    "lucro_da_venda_recalculado": pl.Float64,
    "margem_da_venda_recalculado": pl.Float64,
    "tipo_do_combustivel_ajustado": pl.Utf8,
    "lucro_da_venda_classificado": pl.Utf8,
    "confiabilidade_do_registro": pl.Utf8,
}
